# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SAMPLE_KERNEL_DEV_HELLO)	+= hello.o
obj-$(CONFIG_SAMPLE_KERNEL_DEV_PARAMS)	+= params.o
obj-$(CONFIG_SAMPLE_KERNEL_DEV_CHARDEV)	+= chardev.o
obj-$(CONFIG_SAMPLE_KERNEL_DEV_PROCFS)	+= procfs.o
